### ISSUE TITLE
v4 Support

### ISSUE THREAD

**Issue by stramel** [teerapap/grunt-protractor-runner#165]
Would love to use this with v4. A couple of different approaches already have PRs.
#163
#164

**Comment by Orekhov** [comment]
+1
After Google Chrome v52 update (3rd of August 2016) some of our tests stopped working with protractor v3. 
Only protractor v4 is working.

**Comment by Chexpir** [comment]
Right now, with Chrome 54+ we can't even start with directconnection: true as it would use unsupported ChromeDriver 2.21 from protractor v3. We shouldmove it asap. 
If code maintaners are not available anymore, then other people should be asigned!

**Comment by Orekhov** [comment]
@teerapap, I believe, this issue can be closed now.  Thanks for adding v4 support.

**Comment by stramel** [comment]
Closed with #168
