### ISSUE TITLE
Update to Protractor 5.0.0

### ISSUE THREAD

**Issue by ahmehri** [teerapap/grunt-protractor-runner#182]
Protractor 5.0.0 have been [released](https://github.com/angular/protractor/blob/master/CHANGELOG.md#500). However it's not possible to use it yet because grunt-protractor-runner uses Protractor 4.0.0.

**Comment by azachar** [comment]
+1

**Comment by ansib** [comment]
+1

**Comment by Rednaskel** [comment]
+1

**Comment by Orekhov** [comment]
+1

**Comment by mtheoryx** [comment]
Something else to keep in mind is there are a bunch of breaking changes in 5.0.0

https://github.com/angular/protractor/blob/master/CHANGELOG.md#500

**Comment by runderworld** [comment]
5.0.0 has been released and this ticket can be closed.
