### ISSUE TITLE
Chrome 78: cannot process extension, CRX verification failed

### ISSUE THREAD

**Issue by amejiarosario** [teerapap/grunt-protractor-runner#196]
After my chrome got updated to version 78 it stopped working. 
I see these errors: cannot process extension, CRX verification failed

Errors in context:
```
[07:12:16] I/launcher - Running 1 instances of WebDriver
[07:12:16] I/direct - Using ChromeDriver directly...
[07:12:16] E/launcher - unknown error: cannot process extension #1
from unknown error: CRX verification failed: 3
  (Driver info: chromedriver=78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}),platform=Mac OS X 10.14.6 x86_64)
[07:12:16] E/launcher - WebDriverError: unknown error: cannot process extension #1
from unknown error: CRX verification failed: 3
  (Driver info: chromedriver=78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}),platform=Mac OS X 10.14.6 x86_64)
    at Object.checkLegacyResponse (/Users/admejiar/workspace/eos/node_modules/selenium-webdriver/lib/error.js:546:15)
```

**Comment by SergeyAlekseevN** [comment]
I have the same error.

**Comment by SergeyAlekseevN** [comment]
I investigated this problem. The new chrome does not support CX2 extensions. You need to repack your extensions [chrome://extensions/](chrome://extensions/), or download the latest versions from the developers site.

![изображение](https://user-images.githubusercontent.com/1651597/69006556-6a996100-0928-11ea-964d-7d0b06843fe7.png)

**Comment by SergeyAlekseevN** [comment]
Described a detailed answer on a similar problem.
https://stackoverflow.com/questions/58762418/webdriverexception-message-unknown-error-cannot-process-extension-1-from-unk/58899807#58899807

**Comment by amejiarosario** [comment]
Thanks, I disabled the offending extension and now it’s working
