### ISSUE TITLE
Cannot find module 'protractor'

### ISSUE THREAD

**Issue by wlingke** [teerapap/grunt-protractor-runner#32]
I'm getting this error when I run the task. I have protractor installed globally and it runs correctly using command line `protractor`. Not sure what the issue is...

**Comment by samarjit** [comment]
In protractor 3.2.0, in package.json main:'lib/protractor.js' is referred, but this lib directory is not present. node>require('protractor') fails. Once i downgraded protractor to 3.0.0 the lib/protractor.js is file is appeared and the above error goes away. 

So in my current configuration i have 3.2.0 protractor globally installed and 3.0.0 protractor locally installed. For local protractor i had to proj\node_modules\protractor\bin>webdriver-manager update
it will install 
node_modules\protractor\selenium\selenium-server-standalone-2.48.2.jar
node_modules\protractor\selenium\chromedriver_2.20.zip

Hope this info helps someone.
