### ISSUE TITLE
NPM install webdriver-manager update fails

### ISSUE THREAD

**Issue by mgnsharon** [teerapap/grunt-protractor-runner#41]
After up updating to 0.2.2 npm install fails:

```
+ npm install
npm http GET https://registry.npmjs.org/grunt-protractor-runner
npm http 304 https://registry.npmjs.org/grunt-protractor-runner

> grunt-protractor-runner@0.2.2 install /var/lib/jenkins/jobs/DEPLOY-DEV-residential-microsite/workspace/node_modules/grunt-protractor-runner
> ./node_modules/protractor/bin/webdriver-manager update

sh: ./node_modules/protractor/bin/webdriver-manager: No such file or directory
npm ERR! grunt-protractor-runner@0.2.2 install: `./node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the grunt-protractor-runner@0.2.2 install script.
npm ERR! This is most likely a problem with the grunt-protractor-runner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-protractor-runner
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.4.48-45.46.amzn1.x86_64
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! cwd /var/lib/jenkins/jobs/xxx/workspace
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/jenkins/jobs/xxx/workspace/npm-debug.log
npm ERR! not ok code 0
Build step 'Execute shell' marked build as failure
Finished: FAILURE

```

**Comment by seenivasagaperumal** [comment]
I am trying to install in ubuntu 14.0 

i have installed the protractor then i am trying to run the update command.

webdriver-manager update


vasan@vasan-Lenovo-G580:~$ webdriver-manager update
/usr/bin/env: node: No such file or directory

**Comment by rohitgathibandhe** [comment]
Hi Team, I am unable to run webdriver-manager update on Mac. 

Every time I make an attempt to run this command, I am being displayed with message "-bash: webdriver-manager: command not found"

Request urgent help to fix this issue.

**Comment by reddynr** [comment]
Hi team,

I am getting below error. Please advice. Thanks

C:\Users\nancy>node webdriver-manager start
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\nancy\webdriver-manager'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

**Comment by 61ue5peed** [comment]
same with me ^^^^

**Comment by reddynr** [comment]
Hi Eduard,

I have updated in get-hub. Works for me.  I ran this command from Location
C:\Users\xys\AppData\Roaming\npm\node webdriver-manager start

Thanks


Narendra...!

**Comment by 61ue5peed** [comment]
Thank you :)

**Comment by alejandrocfc** [comment]
@yannickcr thank you !!!
