### ISSUE TITLE
Running multiple protractor tests via Grunt??

### ISSUE THREAD

**Issue by DivsBellur** [teerapap/grunt-protractor-runner#42]
Hello,
I would like to run multiple protractor tests via Grunt. Here is how my setup is:
I have test dir with test1Spec.js, test2Spec.js, …., testnSpec.js

I have a configuration file protractorIntegrationTestsConf.js with specs listed like this:
specs: [
'../src/test/integration/test1Spec.js',
'../src/test/integration/test2Spec.js',
'../src/test/integration/test3Spec.js', 
.
.
.
'../src/test/integration/testnSpec.js'
],

And, my Gruntfile.js has the following protractor task in it
protractor: {
options: {
configFile: "config/protractorIntegrationTestsConf.js",
keepAlive: false,
noColor: false,
singleRun: false,
},
run_chrome: {
options: {
args: {
browser: "chrome"
}
}
},
run_firefox: {
options: {
args: {
browser: "firefox"
}
}
},
run_phantomjs: {
options: {
args: {
browser: "phantomjs"
}
}
}
},

When I run my protractor config file with just protractor all the specs get run in sequence they are listed in config file, but when I try to run it via grunt, all the tests start running simultaneously and the grunt build fails. What is that I am doing wrong here in my setup? Can someone please help me?

Thanks,
Divya

**Comment by MahmudulHasan** [comment]
@DivyaAshok i am just curious to know if you were successful on running multiple protractor tests via Grunt. if you can suggest a way it will be helpful for me.
