### ISSUE TITLE
How to pass complex params to protractor from command line?

### ISSUE THREAD

**Issue by dmitry-dedukhin** [teerapap/grunt-protractor-runner#51]
Hi!

In the readme I can see

```
options.args

Type: Object Default value: {}

Arguments passed to the command. These arguments can also be supplied via command-line too.
```

But I can't figure out how I can pass complex params from command line, e.g. this

```
grunt protractor --params.someParam=someVal
```
doesn't work as expected.

**Comment by ciekawy** [comment]
after looking into the code it looks like objectArgs are curently not supported via command line

**Comment by joaoffalcao** [comment]
Anyone of you already find out how to do it?

**Comment by teerapap** [comment]
Current behaviour is you need to pass escaped JSON object string for --params. (Sorry for unclear README.md) 
Please try this
```
--params='{ "location":"some url" }'
```

If you want `--params.location.xxx` behaviour, please join the discussion in #148
